# Generated by Django 5.2.3 on 2025-08-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsphere_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='file/'),
        ),
    ]
